FROM jaspershen/metabolomics-base:latest
MAINTAINER "Xiaotao Shen" shenxt1990@outlook.com

RUN apt-get update \
  && installGithub.r \
    tidymass/masstools \
    tidymass/massdataset \
    tidymass/metid
    

